---
repos:
  - repo: local
    hooks:
      - id: system
        name: Black
        entry: poetry run black .
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: system
        name: isort
        entry: poetry run isort --profile=black .
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: system
        name: yamllint
        entry: poetry run yamllint .
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: system
        name: mypy
        entry: poetry run mypy --show-error-codes --strict .
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: system
        name: pytest
        entry: poetry run pytest -vv .
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: system
        name: Codespell commit message
        entry: poetry run codespell .git/COMMIT_EDITMSG
        pass_filenames: false
        language: system
        stages: [commit-msg]
