---
name: Publish

on:  # yamllint disable-line rule:truthy
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Poetry
        run: pip install poetry

      - name: Build and publish package
        run: |
          poetry config pypi-token.pypi "${{ secrets.pypi_password }}"
          poetry publish --no-interaction --build
